export const tagGroups = {
  meal: ['早餐', '正餐', '夜宵'],
  scene: ['到店', '宿舍'],
  staple: ['米饭', '面', '粉', '包子', '小吃', '快餐', '汤类'],
  taste: ['清淡', '口味适中', '重口', '辣', '不辣', '热乎'],
  budget: ['便宜', '普通价', '稍贵'],
  mood: ['快速解决', '稳定兜底', '想吃热乎的', '管饱', '可加饭', '外卖', '盖饭', '聚餐', '选择多'],
};

const items = [
  ['西区一楼饺子', ['正餐', '到店', '小吃', '热乎', '口味适中', '普通价', '稳定兜底'], '离得近，脑子空了也能点。', { displayName: '饺子', place: '西区一楼' }],
  ['西区一楼面', ['正餐', '到店', '面', '热乎', '口味适中', '普通价', '稳定兜底'], '一碗热面，把这顿先安顿住。', { displayName: '面', place: '西区一楼' }],
  ['西区三楼汉堡店', ['正餐', '到店', '快餐', '口味适中', '普通价', '快速解决'], '赶时间的时候，别和菜单较劲。', { displayName: '汉堡', place: '西区三楼' }],
  ['西区三楼脆皮鸡饭', ['正餐', '到店', '米饭', '重口', '普通价', '稳定兜底'], '想吃米饭，就让鸡腿出来干活。', { displayName: '脆皮鸡饭', place: '西区三楼' }],
  ['西区三楼湘菜自选盒饭', ['正餐', '到店', '米饭', '辣', '普通价', '稳定兜底'], '菜自己挑，今天别太委屈胃。', { displayName: '湘菜自选盒饭', place: '西区三楼' }],
  ['芒果一楼炒饭', ['正餐', '到店', '米饭', '口味适中', '普通价', '稳定兜底'], '碳水出场，纠结退下。', { displayName: '炒饭', place: '芒果一楼' }],
  ['芒果二楼石锅', ['正餐', '到店', '米饭', '热乎', '普通价', '想吃热乎的'], '端上来还冒热气，像顿正经饭。', { displayName: '石锅', place: '芒果二楼' }],
  ['芒果二楼自选', ['正餐', '到店', '米饭', '口味适中', '普通价', '稳定兜底'], '选择权给你，锅不背给我。', { displayName: '自选盒饭', place: '芒果二楼' }],
  ['东区二楼板凳面', ['正餐', '到店', '面', '热乎', '口味适中', '普通价', '想吃热乎的'], '面端上来，下午就有着落了。', { displayName: '板凳面', place: '东区二楼' }],
  ['东区三楼麦当劳', ['正餐', '到店', '快餐', '普通价', '稳定兜底'], '今天不想猜口味，就交给金拱门。', { displayName: '麦当劳', place: '东区三楼', weight: 5 }],
  ['KFC（芒果一楼）', ['正餐', '到店', '快餐', '普通价', '稳定兜底', '选择多'], '离得近，想吃炸鸡不用走剧情。', { displayName: 'KFC', place: '芒果一楼', area: '芒果', floor: '一楼', type: ['快餐'], weight: 9 }],
  ['KFC（亨顺广场一楼）', ['正餐', '到店', '快餐', '普通价', '稳定兜底', '选择多'], '这家选择多一点，适合认真挑两眼。', { displayName: 'KFC', place: '亨顺广场一楼', area: '校外', floor: '一楼', type: ['快餐'], weight: 9 }],
  ['猪脚饭', ['正餐', '到店', '米饭', '重口', '普通价', '管饱', '稳定兜底', '可加饭'], '饿得明显时，猪脚饭很懂事。', { displayName: '猪脚饭', place: '超级卤力 / 亨顺二楼', area: '校外', floor: '二楼', type: ['米饭'], weight: 7 }],
  ['猪脚饭', ['正餐', '宿舍', '米饭', '重口', '普通价', '管饱', '稳定兜底', '可加饭', '外卖'], '饭送到门口，今天少走几步。', { displayName: '猪脚饭', place: '宿舍', scene: '宿舍', area: '宿舍', floor: '宿舍', type: ['米饭'], weight: 7 }],
  ['黄焖鸡', ['正餐', '到店', '米饭', '热乎', '口味适中', '普通价', '稳定兜底'], '汤汁拌饭，快乐很具体。', { displayName: '黄焖鸡', place: '老友记 / 亨顺二楼', area: '校外', floor: '二楼', type: ['米饭'], weight: 5 }],
  ['黄焖鸡', ['正餐', '宿舍', '米饭', '热乎', '口味适中', '普通价', '稳定兜底', '外卖'], '宿舍吃黄焖鸡，桌子小也能开饭。', { displayName: '黄焖鸡', place: '宿舍', scene: '宿舍', area: '宿舍', floor: '宿舍', type: ['米饭'], weight: 7 }],
  ['兰州拉面（科技园）', ['正餐', '到店', '面', '热乎', '清淡', '普通价'], '热汤热面，适合把人拉回状态。', { displayName: '兰州拉面', place: '科技园' }],
  ['兰州拉面（亨顺广场）', ['正餐', '到店', '面', '热乎', '清淡', '普通价'], '清清爽爽一碗，别把饭吃复杂了。', { displayName: '兰州拉面', place: '亨顺广场' }],
  ['牛肉板面', ['正餐', '到店', '面', '热乎', '重口', '普通价'], '想吃重一点，板面会接住你。', { displayName: '板面', place: '张记 / 亨顺一楼', area: '校外', floor: '一楼', type: ['面'], weight: 3 }],
  ['羊汤', ['正餐', '到店', '汤类', '热乎', '口味适中', '普通价', '想吃热乎的'], '喝口热汤，胃先点个头。', { displayName: '羊汤', place: '羊汤馆 / 亨顺一楼', area: '校外', floor: '一楼', type: ['汤类'], weight: 6 }],
  ['米线', ['正餐', '到店', '粉', '热乎', '口味适中', '普通价'], '这顿想轻松点，米线可以上桌。', { displayName: '米线', place: '过桥米线 / 亨顺一楼', area: '校外', floor: '一楼', type: ['粉'], weight: 5 }],
  ['螺蛳粉（肥姨妈）', ['正餐', '到店', '粉', '辣', '重口', '普通价'], '想换个味道，就别装清淡了。', { displayName: '螺蛳粉', place: '肥姨妈' }],
  ['螺蛳粉（经典）', ['正餐', '到店', '粉', '辣', '重口', '普通价'], '这一口很直接，适合今天嘴馋。', { displayName: '螺蛳粉', place: '经典' }],
  ['麻辣拌/烫（小谷姐姐）', ['正餐', '到店', '小吃', '辣', '重口', '普通价'], '想吃什么夹什么，主打一个随心。', { displayName: '麻辣拌/烫', place: '小谷姐姐' }],
  ['麻辣拌/烫（张亮麻辣烫）', ['正餐', '到店', '小吃', '辣', '重口', '普通价'], '菜多到能拖延三分钟选择困难。', { displayName: '麻辣拌/烫', place: '张亮麻辣烫' }],
  ['重庆小面', ['正餐', '到店', '面', '辣', '重口', '便宜'], '便宜一碗，辣得有存在感。', { displayName: '重庆小面', place: '重庆小面面馆 / 亨顺一楼', area: '校外', floor: '一楼', type: ['面'], weight: 3 }],
  ['犟骨头', ['正餐', '到店', '米饭', '重口', '稍贵', '盖饭'], '想吃肉多一点，就别客气。', { displayName: '犟骨头盖饭', place: '犟骨头 / 亨顺广场一楼', area: '校外', floor: '一楼', type: ['米饭'], weight: 3 }],
  ['犟骨头', ['正餐', '宿舍', '米饭', '重口', '稍贵', '盖饭', '外卖'], '盖饭到宿舍，桌面马上有排面。', { displayName: '犟骨头盖饭', place: '宿舍', scene: '宿舍', area: '宿舍', floor: '宿舍', type: ['米饭'], weight: 3 }],
  ['烤冷面', ['正餐', '宿舍', '小吃', '口味适中', '便宜', '快速解决'], '不想大动干戈，烤冷面够应付。', { displayName: '烤冷面', place: '宿舍', scene: '宿舍', area: '宿舍', floor: '宿舍', type: ['小吃'], weight: 3 }],
  ['炒饭', ['正餐', '宿舍', '米饭', '口味适中', '便宜', '稳定兜底', '快速解决'], '一盒炒饭，宿舍开饭不用仪式。', { displayName: '炒饭', place: '宿舍', scene: '宿舍', area: '宿舍', floor: '宿舍', type: ['米饭'], weight: 6 }],
  ['西北面馆', ['正餐', '到店', '面', '热乎', '口味适中', '普通价'], '想吃面，又不想冒险，去这家。', { displayName: '面馆', place: '西北面馆 / 亨顺一楼', area: '校外', floor: '一楼', type: ['面'], weight: 3 }],
  ['江西菜馆', ['正餐', '到店', '米饭', '辣', '普通价', '聚餐'], '适合叫上人一起吃，菜会热闹点。', { displayName: '江西菜', place: '江西菜馆', area: '校外', floor: '校外', type: ['米饭'], weight: 3 }],
  ['火锅鸡', ['正餐', '到店', '汤类', '热乎', '重口', '稍贵', '聚餐'], '这顿适合慢慢吃，别赶。', { displayName: '火锅鸡', place: '校外', area: '校外', floor: '校外', type: ['汤类'], weight: 2 }],
  ['麦当劳', ['正餐', '宿舍', '快餐', '普通价', '稳定兜底'], '带回宿舍，边吃边放空。', { displayName: '麦当劳', place: '宿舍', weight: 5 }],
  ['麻辣拌/烫', ['正餐', '宿舍', '小吃', '辣', '重口', '普通价'], '拌一盒回去，慢慢吃也不尴尬。', { displayName: '麻辣拌/烫', place: '宿舍' }],
];

const breakfastItems = [
  ['麻酱鸡丝肉干面', ['早餐'], '早八不讲道理，面先讲。', { displayName: '麻酱鸡丝肉干面', place: '西区芒果一楼 KFC', scene: '早餐', area: '西区芒果一楼 KFC', floor: '西区芒果一楼 KFC', type: ['早餐'], weight: 8 }],
  ['芝士猪柳蛋帕尼尼', ['早餐'], '拿着就能走，别和早晨拉扯。', { displayName: '芝士猪柳蛋帕尼尼', place: '西区芒果一楼 KFC', scene: '早餐', area: '西区芒果一楼 KFC', floor: '西区芒果一楼 KFC', type: ['早餐'], weight: 8 }],
  ['芝士猪柳帕尼尼', ['早餐'], '咬两口就能上路，适合赶点。', { displayName: '芝士猪柳帕尼尼', place: '西区芒果一楼 KFC', scene: '早餐', area: '西区芒果一楼 KFC', floor: '西区芒果一楼 KFC', type: ['早餐'], weight: 8 }],
  ['芝士鸡肉帕尼尼（轻盈版）', ['早餐'], '早上别太撑，轻一点刚好。', { displayName: '芝士鸡肉帕尼尼（轻盈版）', place: '西区芒果一楼 KFC', scene: '早餐', area: '西区芒果一楼 KFC', floor: '西区芒果一楼 KFC', type: ['早餐'], weight: 8 }],
  ['芝士鸡肉帕尼尼', ['早餐'], '热乎一份，赶路也不狼狈。', { displayName: '芝士鸡肉帕尼尼', place: '西区芒果一楼 KFC', scene: '早餐', area: '西区芒果一楼 KFC', floor: '西区芒果一楼 KFC', type: ['早餐'], weight: 8 }],
  ['皮蛋瘦肉粥', ['早餐'], '胃还没醒透，粥先来值班。', { displayName: '皮蛋瘦肉粥', place: '西区芒果一楼 KFC', scene: '早餐', area: '西区芒果一楼 KFC', floor: '西区芒果一楼 KFC', type: ['早餐'], weight: 8 }],
  ['八宝粥', ['早餐'], '不想排队，便利店就是退路。', { displayName: '八宝粥', place: '便利店', scene: '早餐', area: '便利店', floor: '便利店', type: ['早餐'], weight: 7 }],
  ['莲子粥', ['早餐'], '拎走一罐，早晨少一道题。', { displayName: '莲子粥', place: '便利店', scene: '早餐', area: '便利店', floor: '便利店', type: ['早餐'], weight: 7 }],
  ['玉米粥', ['早餐'], '甜一点，早上没那么难开机。', { displayName: '玉米粥', place: '便利店', scene: '早餐', area: '便利店', floor: '便利店', type: ['早餐'], weight: 7 }],
  ['速食面包', ['早餐'], '时间不够，面包来补位。', { displayName: '速食面包', place: '便利店', scene: '早餐', area: '便利店', floor: '便利店', type: ['早餐'], weight: 6 }],
  ['包子', ['早餐'], '今天先别整复杂的，包子够用。', { displayName: '包子', place: '便利店', scene: '早餐', area: '便利店', floor: '便利店', type: ['早餐'], weight: 7 }],
];

const typeTags = new Set(['米饭', '面', '粉', '包子', '小吃', '快餐', '汤类']);

function inferArea(place) {
  if (place.startsWith('西区')) return '西区食堂';
  if (place.startsWith('东区')) return '东区食堂';
  if (place.startsWith('芒果')) return '芒果';
  if (place === '宿舍') return '宿舍';
  return '校外';
}

function inferFloor(place, area) {
  const floor = place.match(/(一楼|二楼|三楼)/)?.[1];
  if (floor) return floor;
  if (area === '宿舍') return '宿舍';
  if (area === '校外') return '校外';
  return '';
}

function inferType(name, tags) {
  const types = tags.filter((tag) => typeTags.has(tag));
  if (name.includes('汤') || name.includes('火锅鸡')) {
    types.push('汤类');
  }
  return [...new Set(types)];
}

function inferWeight(tags) {
  if (tags.includes('稳定兜底')) return 7;
  if (tags.includes('快速解决')) return 6;
  if (tags.includes('稍贵')) return 4;
  return 5;
}

export const defaultFoods = items.map(([name, tags, reason, meta = {}], index) => ({
  id: `default-${index + 1}`,
  name,
  displayName: meta.displayName || name,
  place: meta.place || '',
  scene: meta.scene || (meta.place === '宿舍' ? '宿舍' : '到店'),
  area: meta.area || inferArea(meta.place || ''),
  floor: meta.floor || inferFloor(meta.place || '', meta.area || inferArea(meta.place || '')),
  type: meta.type || inferType(name, tags),
  tags,
  reason,
  weight: meta.weight || inferWeight(tags),
  enabled: meta.enabled ?? true,
  favorite: false,
  avoidUntil: null,
}));

export const defaultBreakfastFoods = breakfastItems.map(([name, tags, reason, meta = {}], index) => ({
  id: `breakfast-${index + 1}`,
  name,
  displayName: meta.displayName || name,
  place: meta.place || '',
  scene: meta.scene || '早餐',
  area: meta.area || inferArea(meta.place || ''),
  floor: meta.floor || inferFloor(meta.place || '', meta.area || inferArea(meta.place || '')),
  type: meta.type || inferType(name, tags),
  tags,
  reason,
  weight: meta.weight || inferWeight(tags),
  enabled: meta.enabled ?? true,
  favorite: false,
  avoidUntil: 0,
}));

export const defaultInstantNoodles = [
  {
    id: 'instant-0',
    brand: '宿舍',
    name: '泡面',
    displayName: '泡面',
    type: ['泡面'],
    tags: ['热乎', '便宜', '快速解决'],
    reason: '都这个点了，一碗先顶住。',
    weight: 5,
    enabled: true,
  },
  {
    id: 'instant-1',
    brand: '康师傅',
    name: '康师傅老坛酸菜牛肉面',
    displayName: '老坛酸菜牛肉面',
    type: ['泡面'],
    tags: ['酸辣', '牛肉', '汤面'],
    reason: '酸菜这口熟，夜里不用猜。',
    weight: 5,
    enabled: true,
  },
  {
    id: 'instant-2',
    brand: '康师傅',
    name: '康师傅红烧牛肉面',
    displayName: '红烧牛肉面',
    type: ['泡面'],
    tags: ['红烧', '牛肉', '汤面', '经典'],
    reason: '想不出来的时候，红烧会自己站出来。',
    weight: 5,
    enabled: true,
  },
  {
    id: 'instant-3',
    brand: '康师傅',
    name: '康师傅番茄鸡蛋牛肉面',
    displayName: '番茄鸡蛋牛肉面',
    type: ['泡面'],
    tags: ['番茄', '鸡蛋', '牛肉', '汤面'],
    reason: '番茄汤底柔一点，夜里好入口。',
    weight: 5,
    enabled: true,
  },
  {
    id: 'instant-4',
    brand: '康师傅',
    name: '康师傅香辣牛肉面',
    displayName: '香辣牛肉面',
    type: ['泡面'],
    tags: ['香辣', '牛肉', '汤面'],
    reason: '想吃点辣，就让它上场。',
    weight: 5,
    enabled: true,
  },
  {
    id: 'instant-5',
    brand: '康师傅',
    name: '康师傅藤椒牛肉面',
    displayName: '藤椒牛肉面',
    type: ['泡面'],
    tags: ['藤椒', '牛肉', '麻', '汤面'],
    reason: '藤椒这口有记忆点，别天天红烧。',
    weight: 5,
    enabled: true,
  },
  {
    id: 'instant-6',
    brand: '康师傅',
    name: '康师傅招牌猪骨汤',
    displayName: '招牌猪骨汤',
    type: ['泡面'],
    tags: ['猪骨', '汤面', '热汤'],
    reason: '汤底厚一点，三分钟也像回事。',
    weight: 5,
    enabled: true,
  },
  {
    id: 'instant-7',
    brand: '康师傅',
    name: '康师傅重庆小面',
    displayName: '重庆小面',
    type: ['泡面'],
    tags: ['小面', '辣', '重口', '拌面'],
    reason: '想吃重口，小面不用铺垫。',
    weight: 5,
    enabled: true,
  },
  {
    id: 'instant-8',
    brand: '康师傅',
    name: '康师傅酸酸辣辣豚骨汤面',
    displayName: '酸酸辣辣豚骨汤面',
    type: ['泡面'],
    tags: ['酸辣', '豚骨', '汤面'],
    reason: '酸辣加豚骨，夜里也别太寡淡。',
    weight: 5,
    enabled: true,
  },
  {
    id: 'instant-9',
    brand: '统一',
    name: '统一红烧牛肉面',
    displayName: '红烧牛肉面',
    type: ['泡面'],
    tags: ['红烧', '牛肉', '汤面', '经典'],
    reason: '红烧老朋友，半夜也认路。',
    weight: 5,
    enabled: true,
  },
  {
    id: 'instant-10',
    brand: '统一',
    name: '统一藤椒牛肉面',
    displayName: '藤椒牛肉面',
    type: ['泡面'],
    tags: ['藤椒', '牛肉', '麻', '汤面'],
    reason: '藤椒换个频道，别老一套。',
    weight: 5,
    enabled: true,
  },
  {
    id: 'instant-11',
    brand: '统一',
    name: '统一老坛酸菜牛肉面',
    displayName: '老坛酸菜牛肉面',
    type: ['泡面'],
    tags: ['酸辣', '牛肉', '汤面'],
    reason: '酸菜口一开，夜宵就有方向。',
    weight: 5,
    enabled: true,
  },
  {
    id: 'instant-12',
    brand: '统一',
    name: '统一茄皇牛肉面',
    displayName: '茄皇牛肉面',
    type: ['泡面'],
    tags: ['番茄', '牛肉', '汤面'],
    reason: '番茄味浓，汤也能喝两口。',
    weight: 5,
    enabled: true,
  },
  {
    id: 'instant-13',
    brand: '统一',
    name: '统一茄皇鸡蛋面',
    displayName: '茄皇鸡蛋面',
    type: ['泡面'],
    tags: ['番茄', '鸡蛋', '汤面'],
    reason: '番茄鸡蛋，夜里别吃太硬。',
    weight: 5,
    enabled: true,
  },
  {
    id: 'instant-14',
    brand: '统一粉面蛋肉肠',
    name: '统一粉面蛋肉肠诱惑酸麻味',
    displayName: '诱惑酸麻味',
    type: ['泡面'],
    tags: ['酸麻', '粉面蛋肉肠', '重口'],
    reason: '酸麻这一口，适合馋劲上来。',
    weight: 5,
    enabled: true,
  },
  {
    id: 'instant-15',
    brand: '统一粉面蛋肉肠',
    name: '统一粉面蛋肉肠金汤肥牛味',
    displayName: '金汤肥牛味',
    type: ['泡面'],
    tags: ['金汤', '肥牛', '粉面蛋肉肠'],
    reason: '金汤肥牛，像给泡面加了点排场。',
    weight: 5,
    enabled: true,
  },
  {
    id: 'instant-16',
    brand: '合味道',
    name: '合味道香辣海鲜风味',
    displayName: '香辣海鲜风味',
    type: ['桶面'],
    tags: ['香辣', '海鲜', '桶面'],
    reason: '小杯海鲜，适合不想洗碗的夜。',
    weight: 5,
    enabled: true,
  },
  {
    id: 'instant-17',
    brand: '合味道',
    name: '合味道赤海鲜浓虾汤风味',
    displayName: '赤海鲜浓虾汤风味',
    type: ['桶面'],
    tags: ['海鲜', '浓虾', '桶面', '热汤'],
    reason: '虾汤味出来了，宿舍也有点香。',
    weight: 5,
    enabled: true,
  },
  {
    id: 'instant-18',
    brand: '合味道',
    name: '合味道冬阴功风味',
    displayName: '冬阴功风味',
    type: ['桶面'],
    tags: ['冬阴功', '酸辣', '海鲜', '桶面'],
    reason: '冬阴功这口，适合突然想换风景。',
    weight: 5,
    enabled: true,
  },
  {
    id: 'instant-19',
    brand: '合味道',
    name: '合味道五香牛肉风味',
    displayName: '五香牛肉风味',
    type: ['桶面'],
    tags: ['五香', '牛肉', '桶面'],
    reason: '五香牛肉，像夜里的一张安全牌。',
    weight: 5,
    enabled: true,
  },
  {
    id: 'instant-20',
    brand: '汤达人',
    name: '汤达人日式豚骨拉面',
    displayName: '日式豚骨拉面',
    type: ['泡面'],
    tags: ['豚骨', '拉面', '热汤'],
    reason: '豚骨汤热乎，先把胃安静下来。',
    weight: 5,
    enabled: true,
  },
  {
    id: 'instant-21',
    brand: '汤达人',
    name: '汤达人酸酸甜甜罗宋汤面',
    displayName: '酸酸甜甜罗宋汤面',
    type: ['泡面'],
    tags: ['罗宋汤', '酸甜', '汤面'],
    reason: '酸甜口轻一点，夜里不折腾。',
    weight: 5,
    enabled: true,
  },
  {
    id: 'instant-22',
    brand: '汤达人',
    name: '汤达人酸酸辣辣豚骨面',
    displayName: '酸酸辣辣豚骨面',
    type: ['泡面'],
    tags: ['酸辣', '豚骨', '汤面'],
    reason: '酸辣豚骨，馋的时候够交差。',
    weight: 5,
    enabled: true,
  },
  {
    id: 'instant-23',
    brand: '汤达人',
    name: '汤达人肥汁米线',
    displayName: '肥汁米线',
    type: ['粉'],
    tags: ['米线', '重口', '热汤'],
    reason: '米线换个口感，别总泡同一种面。',
    weight: 5,
    enabled: true,
  },
  {
    id: 'instant-24',
    brand: '汤达人',
    name: '汤达人韩式辣牛肉汤面',
    displayName: '韩式辣牛肉汤面',
    type: ['泡面'],
    tags: ['韩式', '辣', '牛肉', '汤面'],
    reason: '韩式辣牛肉，嘴馋时别装淡定。',
    weight: 5,
    enabled: true,
  },
  {
    id: 'instant-25',
    brand: '杨掌柜粉面菜蛋',
    name: '杨掌柜粉面菜蛋诱惑酸麻味',
    displayName: '诱惑酸麻味',
    type: ['粉面菜蛋'],
    tags: ['酸麻', '粉面菜蛋', '重口'],
    reason: '酸麻味上来，馋劲能交代。',
    weight: 5,
    enabled: true,
  },
  {
    id: 'instant-26',
    brand: '杨掌柜粉面菜蛋',
    name: '杨掌柜粉面菜蛋河南胡辣汤味',
    displayName: '河南胡辣汤味',
    type: ['粉面菜蛋'],
    tags: ['胡辣汤', '粉面菜蛋', '热汤'],
    reason: '想喝浓一点，胡辣汤味能顶上。',
    weight: 5,
    enabled: true,
  },
  {
    id: 'instant-27',
    brand: '杨掌柜粉面菜蛋',
    name: '杨掌柜粉面菜蛋番茄炖牛腩味',
    displayName: '番茄炖牛腩味',
    type: ['粉面菜蛋'],
    tags: ['番茄', '牛腩', '粉面菜蛋'],
    reason: '番茄牛腩，夜里吃着不干巴。',
    weight: 5,
    enabled: true,
  },
  {
    id: 'instant-28',
    brand: '杨掌柜粉面菜蛋',
    name: '杨掌柜粉面菜蛋藤椒沸腾鱼味',
    displayName: '藤椒沸腾鱼味',
    type: ['粉面菜蛋'],
    tags: ['藤椒', '鱼', '粉面菜蛋', '麻'],
    reason: '藤椒鱼这口明显，适合换换嘴。',
    weight: 5,
    enabled: true,
  },
  {
    id: 'instant-29',
    brand: '杨掌柜粉面菜蛋',
    name: '杨掌柜粉面菜蛋老母鸡汤味',
    displayName: '老母鸡汤味',
    type: ['粉面菜蛋'],
    tags: ['鸡汤', '粉面菜蛋', '热汤'],
    reason: '鸡汤味温一点，夜里别太硬来。',
    weight: 5,
    enabled: true,
  },
  {
    id: 'instant-30',
    brand: '杨掌柜粉面菜蛋',
    name: '杨掌柜粉面菜蛋螺蛳粉味',
    displayName: '螺蛳粉味',
    type: ['粉面菜蛋'],
    tags: ['螺蛳粉', '酸辣', '粉面菜蛋'],
    reason: '螺蛳粉味在场，宿舍先通个气。',
    weight: 5,
    enabled: true,
  },
  {
    id: 'instant-31',
    brand: '杨掌柜粉面菜蛋',
    name: '杨掌柜粉面菜蛋酸菜牛肉味',
    displayName: '酸菜牛肉味',
    type: ['粉面菜蛋'],
    tags: ['酸菜', '牛肉', '粉面菜蛋'],
    reason: '酸菜牛肉，熟悉到不用介绍。',
    weight: 5,
    enabled: true,
  },
  {
    id: 'instant-32',
    brand: '杨掌柜粉面菜蛋',
    name: '杨掌柜粉面菜蛋香辣酸豆角味',
    displayName: '香辣酸豆角味',
    type: ['粉面菜蛋'],
    tags: ['香辣', '酸豆角', '粉面菜蛋'],
    reason: '酸豆角加辣，嘴巴会先同意。',
    weight: 5,
    enabled: true,
  },
  {
    id: 'instant-33',
    brand: '杨掌柜粉面菜蛋',
    name: '杨掌柜粉面菜蛋重庆火锅味',
    displayName: '重庆火锅味',
    type: ['粉面菜蛋'],
    tags: ['火锅', '辣', '粉面菜蛋', '重口'],
    reason: '火锅味一开，夜宵突然认真了。',
    weight: 5,
    enabled: true,
  },
];
