export const tagGroups = {
  meal: ['早餐', '正餐', '夜宵'],
  scene: ['到店', '宿舍'],
  staple: ['米饭', '面', '粉', '包子', '小吃', '快餐', '汤类'],
  taste: ['清淡', '口味适中', '重口', '辣', '不辣', '热乎'],
  budget: ['便宜', '普通价', '稍贵'],
  mood: ['快速解决', '稳定兜底', '想吃热乎的', '管饱', '可加饭', '外卖', '盖饭', '聚餐', '选择多'],
};

const items = [
  ['西区一楼饺子', ['正餐', '到店', '小吃', '热乎', '口味适中', '普通价', '稳定兜底'], '离得近，适合快速解决一顿。', { displayName: '饺子', place: '西区一楼' }],
  ['西区一楼面', ['正餐', '到店', '面', '热乎', '口味适中', '普通价', '稳定兜底'], '热乎管饱，不知道吃什么时很稳。', { displayName: '面', place: '西区一楼' }],
  ['西区三楼汉堡店', ['正餐', '到店', '快餐', '口味适中', '普通价', '快速解决'], '出餐快，适合赶时间。', { displayName: '汉堡', place: '西区三楼' }],
  ['西区三楼脆皮鸡饭', ['正餐', '到店', '米饭', '重口', '普通价', '稳定兜底'], '选择稳定，不容易踩雷。', { displayName: '脆皮鸡饭', place: '西区三楼' }],
  ['西区三楼湘菜自选盒饭', ['正餐', '到店', '米饭', '辣', '普通价', '稳定兜底'], '菜多好搭，适合正餐。', { displayName: '湘菜自选盒饭', place: '西区三楼' }],
  ['芒果一楼炒饭', ['正餐', '到店', '米饭', '口味适中', '普通价', '稳定兜底'], '适合不知道吃什么时兜底。', { displayName: '炒饭', place: '芒果一楼' }],
  ['芒果二楼石锅', ['正餐', '到店', '米饭', '热乎', '普通价', '想吃热乎的'], '热乎有汤感，适合认真吃一顿。', { displayName: '石锅', place: '芒果二楼' }],
  ['芒果二楼自选', ['正餐', '到店', '米饭', '口味适中', '普通价', '稳定兜底'], '想吃什么自己搭，容错率高。', { displayName: '自选盒饭', place: '芒果二楼' }],
  ['东区二楼板凳面', ['正餐', '到店', '面', '热乎', '口味适中', '普通价', '想吃热乎的'], '热乎管饱，适合正餐。', { displayName: '板凳面', place: '东区二楼' }],
  ['东区三楼麦当劳', ['正餐', '到店', '快餐', '普通价', '稳定兜底'], '选择稳定，不容易踩雷。', { displayName: '麦当劳', place: '东区三楼', weight: 5 }],
  ['KFC（芒果一楼）', ['正餐', '到店', '快餐', '普通价', '稳定兜底', '选择多'], '你本来就爱吃 KFC，离得也近。顺便看看有没有新款。', { displayName: 'KFC', place: '芒果一楼', area: '芒果', floor: '一楼', type: ['快餐'], weight: 9 }],
  ['KFC（亨顺广场一楼）', ['正餐', '到店', '快餐', '普通价', '稳定兜底', '选择多'], '这家更全，周末还有原味鸡套餐。想吃 KFC 时优先看它。', { displayName: 'KFC', place: '亨顺广场一楼', area: '校外', floor: '一楼', type: ['快餐'], weight: 9 }],
  ['猪脚饭', ['正餐', '到店', '米饭', '重口', '普通价', '管饱', '稳定兜底', '可加饭'], '超级卤力的猪脚饭，味道好，能加饭，适合认真吃一顿。', { displayName: '猪脚饭', place: '超级卤力 / 亨顺二楼', area: '校外', floor: '二楼', type: ['米饭'], weight: 7 }],
  ['猪脚饭', ['正餐', '宿舍', '米饭', '重口', '普通价', '管饱', '稳定兜底', '可加饭', '外卖'], '超级卤力的猪脚饭，外卖也稳，能加饭。', { displayName: '猪脚饭', place: '宿舍', scene: '宿舍', area: '宿舍', floor: '宿舍', type: ['米饭'], weight: 7 }],
  ['黄焖鸡', ['正餐', '到店', '米饭', '热乎', '口味适中', '普通价', '稳定兜底'], '老友记的黄焖鸡，热乎下饭，到店吃也可以。', { displayName: '黄焖鸡', place: '老友记 / 亨顺二楼', area: '校外', floor: '二楼', type: ['米饭'], weight: 5 }],
  ['黄焖鸡', ['正餐', '宿舍', '米饭', '热乎', '口味适中', '普通价', '稳定兜底', '外卖'], '老友记的黄焖鸡外卖更适合宿舍吃，热乎下饭。', { displayName: '黄焖鸡', place: '宿舍', scene: '宿舍', area: '宿舍', floor: '宿舍', type: ['米饭'], weight: 7 }],
  ['兰州拉面（科技园）', ['正餐', '到店', '面', '热乎', '清淡', '普通价'], '热乎稳定，适合快速解决。', { displayName: '兰州拉面', place: '科技园' }],
  ['兰州拉面（亨顺广场）', ['正餐', '到店', '面', '热乎', '清淡', '普通价'], '选择稳定，不容易踩雷。', { displayName: '兰州拉面', place: '亨顺广场' }],
  ['牛肉板面', ['正餐', '到店', '面', '热乎', '重口', '普通价'], '张记的板面，在亨顺一楼，离得近，但不是特别想吃面时才考虑。', { displayName: '板面', place: '张记 / 亨顺一楼', area: '校外', floor: '一楼', type: ['面'], weight: 3 }],
  ['羊汤', ['正餐', '到店', '汤类', '热乎', '口味适中', '普通价', '想吃热乎的'], '羊汤馆在亨顺一楼，热乎舒服，适合冷天或晚点吃。', { displayName: '羊汤', place: '羊汤馆 / 亨顺一楼', area: '校外', floor: '一楼', type: ['汤类'], weight: 6 }],
  ['米线', ['正餐', '到店', '粉', '热乎', '口味适中', '普通价'], '过桥米线在亨顺一楼，热乎顺口，适合不知道吃什么时兜底。', { displayName: '米线', place: '过桥米线 / 亨顺一楼', area: '校外', floor: '一楼', type: ['粉'], weight: 5 }],
  ['螺蛳粉（肥姨妈）', ['正餐', '到店', '粉', '辣', '重口', '普通价'], '重口有记忆点，想换口味时合适。', { displayName: '螺蛳粉', place: '肥姨妈' }],
  ['螺蛳粉（经典）', ['正餐', '到店', '粉', '辣', '重口', '普通价'], '味道直接，适合想吃重口。', { displayName: '螺蛳粉', place: '经典' }],
  ['麻辣拌/烫（小谷姐姐）', ['正餐', '到店', '小吃', '辣', '重口', '普通价'], '菜品好搭，适合到店吃。', { displayName: '麻辣拌/烫', place: '小谷姐姐' }],
  ['麻辣拌/烫（张亮麻辣烫）', ['正餐', '到店', '小吃', '辣', '重口', '普通价'], '选择多，适合不知道吃什么时兜底。', { displayName: '麻辣拌/烫', place: '张亮麻辣烫' }],
  ['重庆小面', ['正餐', '到店', '面', '辣', '重口', '便宜'], '便宜热乎，想吃辣面时可以考虑。', { displayName: '重庆小面', place: '重庆小面面馆 / 亨顺一楼', area: '校外', floor: '一楼', type: ['面'], weight: 3 }],
  ['犟骨头', ['正餐', '到店', '米饭', '重口', '稍贵', '盖饭'], '盖饭选择多，想吃肉多一点可以选。', { displayName: '犟骨头盖饭', place: '犟骨头 / 亨顺广场一楼', area: '校外', floor: '一楼', type: ['米饭'], weight: 3 }],
  ['犟骨头', ['正餐', '宿舍', '米饭', '重口', '稍贵', '盖饭', '外卖'], '盖饭能外卖到宿舍，想吃扎实一点可以选。', { displayName: '犟骨头盖饭', place: '宿舍', scene: '宿舍', area: '宿舍', floor: '宿舍', type: ['米饭'], weight: 3 }],
  ['烤冷面', ['正餐', '宿舍', '小吃', '口味适中', '便宜', '快速解决'], '小吃街打包回宿舍，简单垫一口。', { displayName: '烤冷面', place: '宿舍', scene: '宿舍', area: '宿舍', floor: '宿舍', type: ['小吃'], weight: 3 }],
  ['炒饭', ['正餐', '宿舍', '米饭', '口味适中', '便宜', '稳定兜底', '快速解决'], '打包或外卖都方便，回宿舍也能吃饱。', { displayName: '炒饭', place: '宿舍', scene: '宿舍', area: '宿舍', floor: '宿舍', type: ['米饭'], weight: 6 }],
  ['西北面馆', ['正餐', '到店', '面', '热乎', '口味适中', '普通价'], '面食稳定，想吃热乎面时可以去。', { displayName: '面馆', place: '西北面馆 / 亨顺一楼', area: '校外', floor: '一楼', type: ['面'], weight: 3 }],
  ['江西菜馆', ['正餐', '到店', '米饭', '辣', '普通价', '聚餐'], '适合和同学一起去，想吃辣菜时合适。', { displayName: '江西菜', place: '江西菜馆', area: '校外', floor: '校外', type: ['米饭'], weight: 3 }],
  ['火锅鸡', ['正餐', '到店', '汤类', '热乎', '重口', '稍贵', '聚餐'], '适合和同学一起吃，热乎又管饱。', { displayName: '火锅鸡', place: '校外', area: '校外', floor: '校外', type: ['汤类'], weight: 2 }],
  ['麦当劳', ['正餐', '宿舍', '快餐', '普通价', '稳定兜底'], '选择稳定，适合带回宿舍吃。', { displayName: '麦当劳', place: '宿舍', weight: 5 }],
  ['麻辣拌/烫', ['正餐', '宿舍', '小吃', '辣', '重口', '普通价'], '适合带回宿舍慢慢吃。', { displayName: '麻辣拌/烫', place: '宿舍' }],
];

const breakfastItems = [
  ['芒果一楼包子', ['早餐', '到店', '包子', '清淡', '便宜', '快速解决'], '拿了就走，早餐很方便。', { displayName: '包子', place: '芒果一楼' }],
  ['东区二楼小笼包', ['早餐', '到店', '包子', '清淡', '便宜', '快速解决'], '简单省心，适合早上垫一口。', { displayName: '小笼包', place: '东区二楼' }],
  ['沙县馄饨', ['早餐', '到店', '小吃', '清淡', '便宜'], '轻一点也能吃饱。', { displayName: '馄饨', place: '沙县小吃' }],
  ['灌饼', ['早餐', '宿舍', '小吃', '便宜', '快速解决'], '便宜方便，带回宿舍吃刚好。', { displayName: '灌饼', place: '宿舍', scene: '宿舍', area: '宿舍', floor: '宿舍', type: ['小吃'], weight: 3 }],
  ['包子', ['早餐', '宿舍', '包子', '清淡', '便宜', '快速解决'], '早上方便，带回宿舍也合适。', { displayName: '包子', place: '宿舍' }],
];

const typeTags = new Set(['米饭', '面', '粉', '包子', '小吃', '快餐', '汤类']);

function inferArea(place) {
  if (place.startsWith('西区')) return '西区食堂';
  if (place.startsWith('东区')) return '东区食堂';
  if (place.startsWith('芒果')) return '芒果';
  if (place === '宿舍') return '宿舍';
  return '校外';
}

function inferFloor(place, area) {
  const floor = place.match(/(一楼|二楼|三楼)/)?.[1];
  if (floor) return floor;
  if (area === '宿舍') return '宿舍';
  if (area === '校外') return '校外';
  return '';
}

function inferType(name, tags) {
  const types = tags.filter((tag) => typeTags.has(tag));
  if (name.includes('汤') || name.includes('火锅鸡')) {
    types.push('汤类');
  }
  return [...new Set(types)];
}

function inferWeight(tags) {
  if (tags.includes('稳定兜底')) return 7;
  if (tags.includes('快速解决')) return 6;
  if (tags.includes('稍贵')) return 4;
  return 5;
}

export const defaultFoods = items.map(([name, tags, reason, meta = {}], index) => ({
  id: `default-${index + 1}`,
  name,
  displayName: meta.displayName || name,
  place: meta.place || '',
  scene: meta.scene || (meta.place === '宿舍' ? '宿舍' : '到店'),
  area: meta.area || inferArea(meta.place || ''),
  floor: meta.floor || inferFloor(meta.place || '', meta.area || inferArea(meta.place || '')),
  type: meta.type || inferType(name, tags),
  tags,
  reason,
  weight: meta.weight || inferWeight(tags),
  enabled: meta.enabled ?? true,
  favorite: false,
  avoidUntil: null,
}));

export const defaultBreakfastFoods = breakfastItems.map(([name, tags, reason, meta = {}], index) => ({
  id: `breakfast-${index + 1}`,
  name,
  displayName: meta.displayName || name,
  place: meta.place || '',
  scene: meta.scene || (meta.place === '宿舍' ? '宿舍' : '到店'),
  area: meta.area || inferArea(meta.place || ''),
  floor: meta.floor || inferFloor(meta.place || '', meta.area || inferArea(meta.place || '')),
  type: meta.type || inferType(name, tags),
  tags,
  reason,
  weight: meta.weight || inferWeight(tags),
  enabled: meta.enabled ?? true,
  favorite: false,
  avoidUntil: null,
}));

export const defaultInstantNoodles = [
  {
    id: 'instant-0',
    brand: '宿舍',
    name: '泡面',
    displayName: '泡面',
    type: ['泡面'],
    tags: ['热乎', '便宜', '快速解决'],
    reason: '宿舍兜底，简单省心。',
    weight: 5,
    enabled: true,
  },
  {
    id: 'instant-1',
    brand: '康师傅',
    name: '康师傅老坛酸菜牛肉面',
    displayName: '老坛酸菜牛肉面',
    type: ['泡面'],
    tags: ['酸辣', '牛肉', '汤面'],
    reason: '酸菜味熟悉，夜宵吃着稳。',
    weight: 5,
    enabled: true,
  },
  {
    id: 'instant-2',
    brand: '康师傅',
    name: '康师傅红烧牛肉面',
    displayName: '红烧牛肉面',
    type: ['泡面'],
    tags: ['红烧', '牛肉', '汤面', '经典'],
    reason: '经典兜底，想不出来就它。',
    weight: 5,
    enabled: true,
  },
  {
    id: 'instant-3',
    brand: '康师傅',
    name: '康师傅番茄鸡蛋牛肉面',
    displayName: '番茄鸡蛋牛肉面',
    type: ['泡面'],
    tags: ['番茄', '鸡蛋', '牛肉', '汤面'],
    reason: '番茄汤底顺口，不算太冲。',
    weight: 5,
    enabled: true,
  },
  {
    id: 'instant-4',
    brand: '康师傅',
    name: '康师傅香辣牛肉面',
    displayName: '香辣牛肉面',
    type: ['泡面'],
    tags: ['香辣', '牛肉', '汤面'],
    reason: '想吃辣一点，可以选它。',
    weight: 5,
    enabled: true,
  },
  {
    id: 'instant-5',
    brand: '康师傅',
    name: '康师傅藤椒牛肉面',
    displayName: '藤椒牛肉面',
    type: ['泡面'],
    tags: ['藤椒', '牛肉', '麻', '汤面'],
    reason: '藤椒味明显，适合换个口味。',
    weight: 5,
    enabled: true,
  },
  {
    id: 'instant-6',
    brand: '康师傅',
    name: '康师傅招牌猪骨汤',
    displayName: '招牌猪骨汤',
    type: ['泡面'],
    tags: ['猪骨', '汤面', '热汤'],
    reason: '汤底厚一点，吃着踏实。',
    weight: 5,
    enabled: true,
  },
  {
    id: 'instant-7',
    brand: '康师傅',
    name: '康师傅重庆小面',
    displayName: '重庆小面',
    type: ['泡面'],
    tags: ['小面', '辣', '重口', '拌面'],
    reason: '重口一点，适合想换味。',
    weight: 5,
    enabled: true,
  },
  {
    id: 'instant-8',
    brand: '康师傅',
    name: '康师傅酸酸辣辣豚骨汤面',
    displayName: '酸酸辣辣豚骨汤面',
    type: ['泡面'],
    tags: ['酸辣', '豚骨', '汤面'],
    reason: '酸辣加豚骨，味道比较满。',
    weight: 5,
    enabled: true,
  },
  {
    id: 'instant-9',
    brand: '统一',
    name: '统一红烧牛肉面',
    displayName: '红烧牛肉面',
    type: ['泡面'],
    tags: ['红烧', '牛肉', '汤面', '经典'],
    reason: '经典红烧味，稳妥不出错。',
    weight: 5,
    enabled: true,
  },
  {
    id: 'instant-10',
    brand: '统一',
    name: '统一藤椒牛肉面',
    displayName: '藤椒牛肉面',
    type: ['泡面'],
    tags: ['藤椒', '牛肉', '麻', '汤面'],
    reason: '藤椒味清楚，偶尔换换口味。',
    weight: 5,
    enabled: true,
  },
  {
    id: 'instant-11',
    brand: '统一',
    name: '统一老坛酸菜牛肉面',
    displayName: '老坛酸菜牛肉面',
    type: ['泡面'],
    tags: ['酸辣', '牛肉', '汤面'],
    reason: '酸菜口熟悉，夜宵很稳。',
    weight: 5,
    enabled: true,
  },
  {
    id: 'instant-12',
    brand: '统一',
    name: '统一茄皇牛肉面',
    displayName: '茄皇牛肉面',
    type: ['泡面'],
    tags: ['番茄', '牛肉', '汤面'],
    reason: '番茄味浓，吃着顺口。',
    weight: 5,
    enabled: true,
  },
  {
    id: 'instant-13',
    brand: '统一',
    name: '统一茄皇鸡蛋面',
    displayName: '茄皇鸡蛋面',
    type: ['泡面'],
    tags: ['番茄', '鸡蛋', '汤面'],
    reason: '番茄鸡蛋味，轻一点。',
    weight: 5,
    enabled: true,
  },
  {
    id: 'instant-14',
    brand: '统一粉面蛋肉肠',
    name: '统一粉面蛋肉肠诱惑酸麻味',
    displayName: '诱惑酸麻味',
    type: ['泡面'],
    tags: ['酸麻', '粉面蛋肉肠', '重口'],
    reason: '酸麻口明显，想吃重口时选。',
    weight: 5,
    enabled: true,
  },
  {
    id: 'instant-15',
    brand: '统一粉面蛋肉肠',
    name: '统一粉面蛋肉肠金汤肥牛味',
    displayName: '金汤肥牛味',
    type: ['泡面'],
    tags: ['金汤', '肥牛', '粉面蛋肉肠'],
    reason: '金汤肥牛味，比较像一顿饭。',
    weight: 5,
    enabled: true,
  },
  {
    id: 'instant-16',
    brand: '合味道',
    name: '合味道香辣海鲜风味',
    displayName: '香辣海鲜风味',
    type: ['桶面'],
    tags: ['香辣', '海鲜', '桶面'],
    reason: '小杯海鲜味，轻一点。',
    weight: 5,
    enabled: true,
  },
  {
    id: 'instant-17',
    brand: '合味道',
    name: '合味道赤海鲜浓虾汤风味',
    displayName: '赤海鲜浓虾汤风味',
    type: ['桶面'],
    tags: ['海鲜', '浓虾', '桶面', '热汤'],
    reason: '虾汤味明显，换个海鲜口。',
    weight: 5,
    enabled: true,
  },
  {
    id: 'instant-18',
    brand: '合味道',
    name: '合味道冬阴功风味',
    displayName: '冬阴功风味',
    type: ['桶面'],
    tags: ['冬阴功', '酸辣', '海鲜', '桶面'],
    reason: '酸辣香料味，想换口味时吃。',
    weight: 5,
    enabled: true,
  },
  {
    id: 'instant-19',
    brand: '合味道',
    name: '合味道五香牛肉风味',
    displayName: '五香牛肉风味',
    type: ['桶面'],
    tags: ['五香', '牛肉', '桶面'],
    reason: '五香牛肉味，口味比较稳。',
    weight: 5,
    enabled: true,
  },
  {
    id: 'instant-20',
    brand: '汤达人',
    name: '汤达人日式豚骨拉面',
    displayName: '日式豚骨拉面',
    type: ['泡面'],
    tags: ['豚骨', '拉面', '热汤'],
    reason: '豚骨汤底厚，喝汤舒服。',
    weight: 5,
    enabled: true,
  },
  {
    id: 'instant-21',
    brand: '汤达人',
    name: '汤达人酸酸甜甜罗宋汤面',
    displayName: '酸酸甜甜罗宋汤面',
    type: ['泡面'],
    tags: ['罗宋汤', '酸甜', '汤面'],
    reason: '酸甜口顺，没那么重。',
    weight: 5,
    enabled: true,
  },
  {
    id: 'instant-22',
    brand: '汤达人',
    name: '汤达人酸酸辣辣豚骨面',
    displayName: '酸酸辣辣豚骨面',
    type: ['泡面'],
    tags: ['酸辣', '豚骨', '汤面'],
    reason: '酸辣豚骨味，解馋够用。',
    weight: 5,
    enabled: true,
  },
  {
    id: 'instant-23',
    brand: '汤达人',
    name: '汤达人肥汁米线',
    displayName: '肥汁米线',
    type: ['粉'],
    tags: ['米线', '重口', '热汤'],
    reason: '米线口感不同，换换也行。',
    weight: 5,
    enabled: true,
  },
  {
    id: 'instant-24',
    brand: '汤达人',
    name: '汤达人韩式辣牛肉汤面',
    displayName: '韩式辣牛肉汤面',
    type: ['泡面'],
    tags: ['韩式', '辣', '牛肉', '汤面'],
    reason: '辣牛肉汤底，口味偏重。',
    weight: 5,
    enabled: true,
  },
  {
    id: 'instant-25',
    brand: '杨掌柜粉面菜蛋',
    name: '杨掌柜粉面菜蛋诱惑酸麻味',
    displayName: '诱惑酸麻味',
    type: ['粉面菜蛋'],
    tags: ['酸麻', '粉面菜蛋', '重口'],
    reason: '酸麻味比较足，夜宵想换口味时选。',
    weight: 5,
    enabled: true,
  },
  {
    id: 'instant-26',
    brand: '杨掌柜粉面菜蛋',
    name: '杨掌柜粉面菜蛋河南胡辣汤味',
    displayName: '河南胡辣汤味',
    type: ['粉面菜蛋'],
    tags: ['胡辣汤', '粉面菜蛋', '热汤'],
    reason: '胡辣汤风味，想喝浓汤时选。',
    weight: 5,
    enabled: true,
  },
  {
    id: 'instant-27',
    brand: '杨掌柜粉面菜蛋',
    name: '杨掌柜粉面菜蛋番茄炖牛腩味',
    displayName: '番茄炖牛腩味',
    type: ['粉面菜蛋'],
    tags: ['番茄', '牛腩', '粉面菜蛋'],
    reason: '番茄牛腩味，顺口管饱。',
    weight: 5,
    enabled: true,
  },
  {
    id: 'instant-28',
    brand: '杨掌柜粉面菜蛋',
    name: '杨掌柜粉面菜蛋藤椒沸腾鱼味',
    displayName: '藤椒沸腾鱼味',
    type: ['粉面菜蛋'],
    tags: ['藤椒', '鱼', '粉面菜蛋', '麻'],
    reason: '藤椒鱼味明显，偏重口。',
    weight: 5,
    enabled: true,
  },
  {
    id: 'instant-29',
    brand: '杨掌柜粉面菜蛋',
    name: '杨掌柜粉面菜蛋老母鸡汤味',
    displayName: '老母鸡汤味',
    type: ['粉面菜蛋'],
    tags: ['鸡汤', '粉面菜蛋', '热汤'],
    reason: '鸡汤味更温和，吃着稳。',
    weight: 5,
    enabled: true,
  },
  {
    id: 'instant-30',
    brand: '杨掌柜粉面菜蛋',
    name: '杨掌柜粉面菜蛋螺蛳粉味',
    displayName: '螺蛳粉味',
    type: ['粉面菜蛋'],
    tags: ['螺蛳粉', '酸辣', '粉面菜蛋'],
    reason: '螺蛳粉味明显，想吃重口时再选。',
    weight: 5,
    enabled: true,
  },
  {
    id: 'instant-31',
    brand: '杨掌柜粉面菜蛋',
    name: '杨掌柜粉面菜蛋酸菜牛肉味',
    displayName: '酸菜牛肉味',
    type: ['粉面菜蛋'],
    tags: ['酸菜', '牛肉', '粉面菜蛋'],
    reason: '酸菜牛肉味，经典耐吃。',
    weight: 5,
    enabled: true,
  },
  {
    id: 'instant-32',
    brand: '杨掌柜粉面菜蛋',
    name: '杨掌柜粉面菜蛋香辣酸豆角味',
    displayName: '香辣酸豆角味',
    type: ['粉面菜蛋'],
    tags: ['香辣', '酸豆角', '粉面菜蛋'],
    reason: '酸豆角加辣，比较下饭。',
    weight: 5,
    enabled: true,
  },
  {
    id: 'instant-33',
    brand: '杨掌柜粉面菜蛋',
    name: '杨掌柜粉面菜蛋重庆火锅味',
    displayName: '重庆火锅味',
    type: ['粉面菜蛋'],
    tags: ['火锅', '辣', '粉面菜蛋', '重口'],
    reason: '火锅味偏重，想吃辣一点时选。',
    weight: 5,
    enabled: true,
  },
];
